In [4]:
import numpy as np
from sklearn import preprocessing

In [5]:
X = np.array([[1., -1., 2.],
              [2.0, 0., 0.],
              [0., 1., -1.]])

In [16]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

##### this function centres it around the mean that is it makes mean = 0 and var = 1

In [8]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [9]:
X_scaled.std(axis = 0)

array([1., 1., 1.])

In [14]:
# help(np.mean)

In [15]:
scaler = preprocessing.StandardScaler()
scaler.fit(X) # learns the parameters for scaling from training data X

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [17]:
X_test = [[1,1,0]]
scaler.transform(X_test) # transform x_test using the parameters learned from training data X

array([[ 0.        ,  1.22474487, -0.26726124]])