# Numpy
- Numerical python (for dealing with numbers)
- Python's linear algebra library with which we can perform lots of calculations over large amounts of data.
- Numpy also gives us multidimensional arrays (nd arrays)

Numpy arrays have several advantages over normal python lists :

- Memory : less memory requirements
- Speed : Numpy arrays are much faster than normal lists
- Convenience : Because of the functionalities

In [4]:
import numpy as np
li_arr = list(range(100))
np_arr = np.arange(100)
print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
## size of one element in numpy array
print(np_arr.itemsize) # accessing the itemsize attribute of the np_arr object
## size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)

4
400


In [12]:

import sys
a = 10
## size of one element in a list
print(sys.getsizeof(a))

## size of 100 elements in a list
print(sys.getsizeof(a) * len(li_arr))

28
2800


In [19]:
import time
import numpy as np
size = 1000000 # 10**6
def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return t2 - t1
def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b # numpy arrays can be directly added like this
    t2 = time.time()
    return t2 - t1

In [21]:
t_list = addition_using_list()
t_numpy = addition_using_numpy()
print('list = ', t_list * 1000) # milliseconds
print('numpy = ', t_numpy * 1000)

list =  399.0354537963867
numpy =  7.019758224487305


#### See, Numpy arrays are much faster than normal lists in python.

Reason :
- Numpy arrays support vectorization
- Operations in numpy are written very efficiently in C/Fortran

## Creating numpy arrays

Using <code>numpy.array(arraylike_obj[,dtype = whatever_type])</code>

tip: check out the function signature and documentation using <code>Shift+Tab</code>

In [26]:
import numpy as np # np is the alias name now
li = [1, 3, 5, 6, 7.2]
arr = np.array(li)
arr1 = np.array(li, dtype = int)
arr2 = np.array(li, dtype = str)
print(arr)
print(arr1)
print(arr2)

[1.  3.  5.  6.  7.2]
[1 3 5 6 7]
['1' '3' '5' '6' '7.2']


NumPy arrays are homogenous and can contain object of only one type
unlike Python lists which are heterogeneous

In [29]:
a = [1,2,3]
my_arr = np.array(a * 3)
my_arr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
b = np.ones(3)
b

array([1., 1., 1.])

In [32]:
b = np.ones((3,2), dtype = str)
b

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [33]:
b = np.ones((3,2), dtype = int)
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [40]:
z = np.zeros((5,6,3)) # gotta pass the dimension as a tuple
z
# note that there are 5 elements in this array.
# 5 matrices of dimension (6,3)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
f = np.full((3,4),6) 
f

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [93]:
e = np.empty((2,4), dtype = int)
e
# Return a new array of given shape and type, with random values.

array([[1851877746,  539911523, 1919895072, 1920098592],
       [ 544438625, 1763731055, 1734702190, 1948283493]])

In [47]:
import sys
sys.version

'3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]'

### Check out the documentation of the following methods

numpy.arange()

numpy.linspace()

numpy.identity()

numpy.eye()

numpy.random.rand()

numpy.random.randint()

In [103]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
b = np.arange(4,14,2,dtype=float) # [4,14) : a half-open interval
b 

array([ 4.,  6.,  8., 10., 12.])

In [105]:
c = np.linspace(10,20) # both upper and lower limits are inclusive (by default) 
c # 50 samples by default

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [108]:
d = np.linspace(10,15,10,endpoint=False) # Shift-Tab
d

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [112]:
np.identity(3, dtype=int) # only square shape

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [111]:
np.eye(2,3) # shape can be (M,N)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [113]:
np.random.rand(2,3) 
'''
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.
'''

array([[0.52538317, 0.29182128, 0.23520882],
       [0.2497783 , 0.84981104, 0.54027806]])

In [116]:
# generate 5 random values in [0,100)
rando = np.random.rand(5) * 100
rando

array([91.31521311, 96.56029132,  3.15946682, 89.51301671, 96.37044626])

In [211]:
r = np.random.randint(5)
r

0

In [229]:
r = np.random.randint(5,10,size = (3,2))
r

array([[6, 6],
       [9, 5],
       [8, 8]])

In [228]:
# rolling a die
roll_die = np.random.randint(1,7)
roll_die

2

In [231]:
# exercise
import numpy as np
nparray = np.arange(9,50)
for i in nparray:
    print(i,end=" ")


[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [236]:
# ex
'''
You are given a rope of length 5m. Cut the rope into 9 parts such that 
each part is of equal length.
Note: Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.
Output Format :

element1 
element2 
element3
...
'''
a = np.linspace(0,5,num = 10) # both inclusive by default
for i in a:
    print(f'{i:1.2f}')

0.00
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.00


In [2]:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)
arr

array([1, 2, 3, 4, 5])

#### attributes of numpy array
- data
- shape
- dtype
- strides

In [3]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides) # no. of bytes skipped to get to the next element

(5,)
int32
(4,)


In [5]:
# for 2d array
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(3, 4)
int32
(16, 4)


In [4]:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
print(arr[3])
print(li[3])

4
4


In [7]:
## indexing
print(li[1:4])
print(arr[1:4])

[2, 3, 4]
[2 3 4]


In [9]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d[2][3])
print(arr_2d[2][3])
print(arr_2d[2,3])

12
12
12


In [12]:
## slicing in 2d array : access 5,6,7 from the array by slicing
print(li_2d[1][:3])
print(arr_2d[1,:3])

[5, 6, 7]
[5 6 7]


In [18]:

print(li_2d[:3][2])

[9, 10, 11, 12]


In [20]:
x = li_2d[:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [23]:
print(arr_2d[:3,2])
print(arr_2d[:3][2]) # see 

[ 3  7 11]
[ 9 10 11 12]


Notice the difference above (in accessing values from 2d arrays and 2d lists)



In [25]:
print(arr_2d[:3][3]) # throws an error 

IndexError: index 3 is out of bounds for axis 0 with size 3

### This is the 2D matrix
#### _col_0___1____ 2____3

    1   2   3   4  | *row 0*

    5   6   7   8  | *row 1*

    9   10  11  12 | *row 2*

    13  14  15  16 | *row 3*

In [26]:
'''
Let's access 10 11
             14 15
             
'''
# this can be directly done by slicing in numpy 2D arrays
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]


In [3]:
import numpy as np
li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

## add 1 to each element
li = [i+1 for i in li]
li

[1, 2, 3, 4, 5]
[ 3 11 12  5 16]
[18 10 14 15 17]


[2, 3, 4, 5, 6]

In [5]:
print(a)

[12 14 14 13  4]


In [6]:
## see how simple it is, in case of numpy arrays
a = a + 1
a

array([13, 15, 15, 14,  5])

In [6]:
c = a + b
d = a - b
e = a / b
p = a ** b
q = a % b
f = a // b # integer division or floor division
print(c)
print(d)
print(e)
print(p)
print(q)
print(f)

[21 21 26 20 33]
[-15   1  -2 -10  -1]
[0.16666667 1.1        0.85714286 0.33333333 0.94117647]
[  387420489   167620825 -1879048192   452807053           0]
[ 3  1 12  5 16]
[0 1 0 0 0]


### Thus, Mathematical operations become very simple and fast with numpy

In [10]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin()) # index of the min element
print(a.max())
print(a.argmax())

[ 3 11 12  5 16]
47
9.4
3
0
16
4


### logical operations

In [11]:
print(a)
print(b)


[ 3 11 12  5 16]
[18 10 14 15 17]


In [12]:
a > b

array([False,  True, False, False, False])

In [13]:
a == b

array([False, False, False, False, False])

In [14]:
print(np.logical_or(a, b))

[ True  True  True  True  True]


In [15]:
print(np.logical_and(a, b))

[ True  True  True  True  True]


In [16]:
a[2] = 0
print(np.logical_and(a, b))

[ True  True False  True  True]


In [17]:
a

array([ 3, 11,  0,  5, 16])

In [19]:
print(np.logical_not(a))

[False False  True False False]


In [23]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a = np.array(li_2d)
ls_2d = [[1,5,9,0],[1,3,4,6],[1,0,0,1]]
b = np.array(ls_2d)
print(a)
print()
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 5 9 0]
 [1 3 4 6]
 [1 0 0 1]]


In [24]:
a == b

C:\Users\Milanchand Oinam\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [25]:
a > b # throws an error coz the operands should be of same shape

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [29]:
b = np.array([[1,0,0,1],[2,5,10,18],[1,3,2,4],[2,2,2,0]])
print(a)
print(b)
a == b  # element by element comparison

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  0  0  1]
 [ 2  5 10 18]
 [ 1  3  2  4]
 [ 2  2  2  0]]


array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
a > b

array([[False,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Boolean Indexing

In [35]:
## extract elements based on any condition
import numpy as np
b = np.random.randint(0, 20, 8)
b

array([12,  2,  8, 13,  2, 18,  5, 17])

In [36]:
bool_arr = b > 10
bool_arr

array([ True, False, False,  True, False,  True, False,  True])

In [37]:
## print those elements greater than 10
print(b[bool_arr])

[12 13 18 17]


In [38]:
## short
print(b[b>10]) # just pass the boolean condition as index (boolean indexing)

[12 13 18 17]


In [44]:
print(b[(b > 10) & (b < 15)]) # '&' is a bitwise operator

[12 13]


In [46]:
## updating multiple elements at once
c = b
c[:3] = 5
print(c)

[ 5  5  5 13  2 18  5 17]
[ 5  5  5 13  2 18  5 17]


In [47]:
c[c>15] = 100
c

array([  5,   5,   5,  13,   2, 100,   5, 100])

In [49]:
## np.where(<condition>) to see the indices where the condition is satisfied
ind = np.where(c==100)

(array([5, 7], dtype=int64),)

In [51]:
a_li = ['b','g','a','n','s','d','e','f']
a = np.array(a_li)
print(a)
print(b)

['b' 'g' 'a' 'n' 's' 'd' 'e' 'f']
[  5   5   5  13   2 100   5 100]


In [52]:
'''
if b[i] == 100:
    print(a[i])
'''
ind = np.where(b==100)
print(a[ind])


['d' 'f']


Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.
Output Format :

index1 index2 index3 ... 



In [3]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr!=0)[0] # [0] here removes the bounding brackets that would otherwise appear in the output
for i in ind:
    print(i, end = ' ')

0 1 4 

Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Print the index of elements.

Output Format :

index1 index2 index3 ... 


In [5]:
import numpy as np
arr = np.arange(1,20,2)
ind = np.where(arr%3==0)[0]
for i in ind:
    print(i,end=' ')

1 4 7 

##### Odd elements

Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Print the Numpy array.
Output Format :

firstElement secondElement  ... 



In [6]:
import numpy as np
arr = np.arange(1,11)
arr[(arr%2) != 0] = -1
for i in arr:
    print(i, end = ' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

#### Replace Max

Problem Statemnt:
Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
Note: Generate the following array

array([11, 2, 13, 4, 15, 6, 27, 8, 19])

Print the Numpy array.
Output Format :

firstElement
secondElement 
... 



In [10]:
import numpy as np
arr = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
ind = np.where(arr == arr.max())
arr[ind] = 0
for i in arr :
    print(i, end = ' ')

11 2 13 4 15 6 0 8 19 

In [11]:
# OR
#ind = arr.argmax()
# arr[ind] = 0

8

Problem Statemnt:

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Print the Numpy array.
Output Format :

firstElement 

secondElement  
... 



In [15]:
import numpy as np
arr = np.arange(1,11)
ind = np.where((arr>=3) & (arr<=8))
for i in ind:
    arr[i] = -arr[i]
    # arr[i] = np.negative(arr[i])
for i in arr:
    print(i)


1
2
-3
-4
-5
-6
-7
-8
9
10


Problem Statemnt:

Given age and height of 20 students in two different numpy arrays with age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.
Output Format :

age1 height1

age2 height2 
... 



In [7]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind = np.where(height>155)[0] # this is the index of students whose height > 155
for i in ind:
    print(age[i],end=' ')
    print(height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


### Boolean Indexing - 2D

In [11]:
## first let's generate a random 2D array of size (5,6)
import numpy as np
a = np.random.randint(1,30,size=(5,6))
a

array([[15,  1, 28, 19, 25, 22],
       [ 9,  8,  8,  5, 13,  4],
       [13, 22, 13, 29, 11, 11],
       [21, 23,  2,  7,  7, 28],
       [ 2, 13, 28,  5, 29,  1]])

In [16]:
bool_arr = a > 20
print(bool_arr)

[[False False  True False  True  True]
 [False False False False False False]
 [False  True False  True False False]
 [ True  True False False False  True]
 [False False  True False  True False]]


In [17]:
# extract values greater than 20
print(a[bool_arr])

[28 25 22 22 29 21 23 28 28 29]


In [18]:
# if a[i][j] > 20 , then a[i][j] = 100
b = a
b[bool_arr] = 100
print(b)

[[ 15   1 100  19 100 100]
 [  9   8   8   5  13   4]
 [ 13 100  13 100  11  11]
 [100 100   2   7   7 100]
 [  2  13 100   5 100   1]]


Note : the dimension of the boolean index and indexed array should be same, otherwise it throws an error

In [22]:
## let's find out 100's in the last col and update them to 99


[ True False False  True False]
[[ 99  99  99  99  99  99]
 [  9   8   8   5  13   4]
 [ 13 100  13 100  11  11]
 [ 99  99  99  99  99  99]
 [  2  13 100   5 100   1]]


Problem Statemnt:

Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:

 [[21 20 19 18 17]
 
  [16 15 14 13 12]
  
  [11 10  9  8  7]
  
  [ 6  5  4  3  2]]

Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :

[[ 6  5  4  3  2]

[11 10  9  8  7]

[16 15 14 13 12]

[21 20 19 18 17]]



In [26]:
import numpy as np
a = np.arange(21, 1, -1) # generates the input array
a = a.reshape(4, 5) # from 1d to 2d array
sorted_index = a[:, 1].argsort() # sort the indexes of col no. 1 in ascending order of their corresponding values
print(a[sorted_index])

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


#### Numpy broadcasting

In [29]:
import numpy as np
a = np.random.randint(0,20,(3,3))
b = np.random.randint(0,20,3)
print(a)
print()
print(b)

[[18 14  1]
 [ 0  2 17]
 [ 5 14  4]]

[ 6 17 10]


In [30]:
print(a - b) # (3,3) and 3(can also be written as (1,3)) are compatible coz one of them is one

[[ 12  -3  -9]
 [ -6 -15   7]
 [ -1  -3  -6]]


In [31]:
a = np.random.randint(0,20,(2,3))
b = np.random.randint(0,20,(3,2))
print(a)
print(b)

[[13  4 11]
 [ 3 14  8]]
[[16 18]
 [18  8]
 [ 2  3]]


In [32]:
a - b # 2,3 and 3,2 not compatible

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [33]:
b = np.transpose(b)
print(a-b)

[[ -3 -14   9]
 [-15   6   5]]


In [35]:
print(a)
a = np.resize(a, (2,4))
print(a)

[[13  4 11]
 [ 3 14  8]]
[[13  4 11  3]
 [14  8 13  4]]


In [36]:
print(np.resize(a, (2,1)))

[[13]
 [ 4]]


### np.resize()

The new array is formed from the data in the old array, repeated if necessary to fill out the required number of elements. The data are repeated in the order that they are stored in memory.

In [45]:
# this is different from a.resize(new_shape) which is in-place resizing
a.resize((2,1))
a

ValueError: cannot resize this array: it does not own its data

### np.reshape()

Gives a new shape to an array without changing its data.

In [2]:
import numpy as np
a = np.random.randint(1,30,(2,3))
a

array([[26, 24,  7],
       [14, 14,  2]])

In [4]:
b = np.reshape(a,(3,4))
# error means size(no. of elements) must be equal
# 3 * 4 != 6

ValueError: cannot reshape array of size 6 into shape (3,4)

In [10]:
b = np.reshape(a,6) #fine
c = np.reshape(b,(1,6)) # ok
print(b)
print(c)

[26 24  7 14 14  2]
[[26 24  7 14 14  2]]


few more examples of numpy broadcasting

- (3,3) with (3,1) : (3,1) --> (3,3) and then operation performed
- (1,3) with (3,1) : both --> (3,3) and then operation performed
- (1,3) with (1,1) : (1,1) --> (1,3) and then operation performed

In [11]:
import numpy as np
a = np.random.randint(1,30,(3,3))
b = np.random.randint(1,30,(3,1))
print(a)
print(b)
print(a+b) # see it's is (3,3) array

[[ 2 23 19]
 [17  7  2]
 [ 8 24 25]]
[[ 4]
 [11]
 [ 2]]
[[ 6 27 23]
 [28 18 13]
 [10 26 27]]


In [12]:
a = np.random.randint(1,30,(1,3))
b = np.random.randint(1,30,(3,1))
print(a)
print(b)
print(a+b) # see it's is (3,3) array


[[ 9 29  6]]
[[26]
 [23]
 [ 9]]
[[35 55 32]
 [32 52 29]
 [18 38 15]]


In [14]:
a = np.random.randint(1,30,(1,3))
b = np.random.randint(1,30,1) # 1 is 1d and (1,1) is 2d
print(a)
print(b)
print(a+b) # see it's is (1,3) array

[[ 5  1 12]]
[7]
[[12  8 19]]


In [45]:
## year2017.csv
import numpy as np
import csv
# reading the data from the file
file_obj = open('year2017.csv')
file_data = csv.DictReader(file_obj, skipinitialspace = True)

# creating the lists
country = []
killed = []
wounded = []

for row in file_data:
    #print(row)
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])

# convert to numpy array for simpler calculations
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_country = np.array(country)

# handling the missing values
np_killed[np_killed == ''] = '0.0' # boolean indexing technique
np_wounded[np_wounded == ''] = '0.0'

# convert dtype to 'float'
np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

killed_wounded = np_killed + np_wounded

#total number of killed and wounded
print(np.sum(killed_wounded))
#total number of killed and wounded in India
bool_arr = np_country == 'India'
print(np.sum(killed_wounded[bool_arr]))

51372.0
1167.0


0